adding required files for f35-py310 S2I image to built
thoth-station/s2i-thoth pull request #235
Opened 2022-03-08 22:41 UTC by Gregory-Pereira

## Related Issues and Dependencies

Related to https://github.com/thoth-station/s2i-thoth/issues/231

## This introduces a breaking change

- [ ] Yes
- [X] No

## This Pull Request implements

Implements the files required to build a Thoth image of fedora35 with python3.10 using S2I.

## Description

Solely creates the base image, a solver image still needs to be built from this.

2022-03-08 22:42 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | b06d48aec4dc117a5fc05caf1ee2b245be182a8c | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_s2i-thoth/235/pre-commit/1501327218448535552) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=s2i-thoth&pr=235). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/s2i-thoth/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-09 13:51 UTC, goern commented on README.rst
> +.. |s2i-thoth-f34-py39 on Quay| image:: https://quay.io/repository/thoth-station/s2i-thoth-f35-py310/status
this reads f34-py39, a c-n-p-probelm

2022-03-09 13:53 UTC, goern commented
/lgtm
/assign @Gregory-Pereira

2022-03-09 16:24 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2022-03-09 16:24 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **goern** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fs2i-thoth).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/s2i-thoth/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["goern"]} -->

2022-03-09 17:15 UTC, harshad16 requested changes
nice work.
was the s2i_assemble.patch copied from other folders?

and another minor question

2022-03-09 17:15 UTC, harshad16 commented on ubi8-py36/s2i_assemble.patch
> ---- a/assemble	2021-12-07 00:04:23.680648366 -0500
is changes to ubi file intentional ?

2022-03-09 17:24 UTC, Gregory-Pereira commented
> nice work. was the s2i_assemble.patch copied from other folders?
> and another minor question
    > is changes to ubi file intentional ?

1. Yes I copied the file for the s2i_assemble.patch living in the `f34-py39` folder, and went to change anything specific to fedora version 34 or python version 3.9, but there were none. I did this because I wasn't exactly sure how these were meant to be implemented / generated, if there is a better way I am all ears.

2. I did not want to change the UBI assemble patches however, there was some formatting issue in them that made the pre-commit fail. I am guessing it was something in [this commit] that caused it, and I am not sure if changes were forced into master, the pre-commit was down, or the configuration file for precommit changed since then.

2022-03-09 18:29 UTC, harshad16 commented
> 1. Yes I copied the file for the s2i_assemble.patch living in the `f34-py39` folder, and went to change anything specific to fedora version 34 or python version 3.9, but there were none. I did this because I wasn't exactly sure how these were meant to be implemented / generated, if there is a better way I am all ears.

The reason why I asked this is because, the `s2i_assemble.patch` is created based on the difference of the `assemble`  present in the base image and addition we are trying to do from our assemble script. 
As the `assemble` bit can differ from base image to base image, it is good to verify this once.

*. Easiest way to verify: Try to build the image from the dockerfile. (if successful the patch is in good shape)

* How is the patch created (just for your knowledge, don't need to be done for this):
Get the `assemble` from the base image: usually located at `usr/libexec/s2i/assemble`
Remove the bits we don't want , (this can be referenced from other patches)

state the copied assemble script in `a/assemble`
state the removed bit assemble script in `b/assemble`
`diff -u a/assemble b/assemble > assemble.patch`

the resultant patch is what we require.

> 2. I did not want to change the UBI assemble patches however, there was some formatting issue in them that made the pre-commit fail. I am guessing it was something in [this commit](https://github.com/thoth-station/s2i-thoth/commit/60a0ea504dc82dd4063efb7b3358074152baecdb) that caused it, and I am not sure if changes were forced into master, the pre-commit was down, or the configuration file for precommit changed since then.

Thanks for the changes :)

2022-03-09 18:29 UTC, harshad16 commented
/hold

hold till the image build is confirmed.

2022-03-09 18:38 UTC, harshad16 commented
The s2i_assemble.patch script fails with f35 base image to be patched:
```
/usr/libexec/s2i ~
File assemble is read-only; trying to patch anyway
patching file assemble
Hunk #2 FAILED at 23.
1 out of 2 hunks FAILED -- saving rejects to file assemble.rej
```

2022-03-09 18:47 UTC, Gregory-Pereira commented
Got it, thanks Harshad, taking a look now.

2022-03-10 19:06 UTC, Gregory-Pereira commented
Can confirm that the `f35-py310` overlay now builds correctly:
```
$ podman build .
STEP 1/8: FROM registry.fedoraproject.org/f35/python3:0-41.container
...
STEP 8/8: USER 1001
--> Using cache 83dc730284d93fd5378c557bf4a3f1fc58647b0f8279eaab5aeb147de067fc78
--> 83dc730284d
83dc730284d93fd5378c557bf4a3f1fc58647b0f8279eaab5aeb147de067fc78
```

2022-03-10 19:11 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 882e2c27a9b8d31d0376bb5f229f302bd15e1eea | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_s2i-thoth/235/pre-commit/1501998970627428352) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=s2i-thoth&pr=235). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/s2i-thoth/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-10 19:13 UTC, Gregory-Pereira commented
/hold
Working on formatting the `README.rst` file.

2022-03-10 19:18 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 1f8fede6316e6551cc7de41a226fc3491644edbf | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_s2i-thoth/235/pre-commit/1502000713360740352) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=s2i-thoth&pr=235). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/s2i-thoth/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-03-10 19:24 UTC, Gregory-Pereira commented
/unhold
Ready for review.

2022-03-11 09:49 UTC, fridex approved these changes
Changes look really nice to me. I've also verified the resulting container image works. I think this can go in. Thanks! 💯 👍🏻

2022-03-11 09:49 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/s2i-thoth/pull/235#pullrequestreview-906989103" title="Approved">fridex</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fs2i-thoth).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/thoth-station/s2i-thoth/blob/master/OWNERS)~~ [fridex]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-03-11 09:51 UTC, merged